# Arizona voter file/history will upload as a single .zip file with the date of creation as the filename- for instance
# "20180319.zip". History is included in these files, also columns for each election plus party primary the voter participated in and method of voting.
#File also contain occupations! No idea what to do with this.
#This zip contains 14 xlsx files:
#13 COUNTIES - ACTIVE.xlsx
#13 COUNTIES - CANCELED.xlsx
#13 COUNTIES - INACTIVE.xlsx
#13 COUNTIES - SUSPENSE.xlsx
#LEGEND.xlsx
#MARICOPA - ACTIVE - DEM.xlsx
#MARICOPA - ACTIVE - OTHER PARTY STATUSES.xlsx
#MARICOPA - ACTIVE - REP.xlsx
#MARICOPA - CANCELED.xlsx
#MARICOPA - INACTIVE.xlsx
#MARICOPA - SUSPENSE.xlsx
#PIMA - ACTIVE.xlsx
#PIMA - CANCELED.xlsx
#PIMA - INACTIVE.xlsx
file_type: xlsx
state: Arizona
source: boe
file_class: voter_file
voter_id: text_registrant_id
county_identifier: county
birthday_identifier: year_of_birth
voter_status: cde_registrant_status
voter_status_active: A
voter_status_inactive: I
voter_status_suspense: S
voter_status_cancelled: C
voter_status_not_eligible: N
voter_status_not_registered: NR
democratic_party: DEMOCRATIC
republican_party: REPUBLICAN
no_party_affiliation: OTHER
numeric_county: false
date_format: '%m/%d/%Y'
party_identifier: desc_party
primary_key:
  - pre_date
  - post_date
  - VoterID
  - change_type
base_columns:
  pre_date: timestamp
  post_date: timestamp
  VoterID: int
  change_type: text
  pre_value: text
  post_value: text
  state: varchar
generated_columns:
  all_history: text[]
ordered_generated_columns:
  - all_history
has_headers: YES
summary_columns:
  - totals
  - date
  - state
  - ages_18_34
  - ages_35_49
  - ages_50_64
  - ages_65_130
  - Republican
  - Democratic
  - Other
  - county
summary_types:
  - int
  - timestamp
  - text
  - int
  - int
  - int
  - int
  - text
  - text
  - text
  - text
columns:
    county: varchar
    cde_registrant_status: varchar
    cde_registrant_reason: varchar
    cde_name_title: varchar
    text_name_first: varchar
    text_name_middle: varchar
    text_name_last: varchar
    cde_name_suffix: varchar
    year_of_birth: int
    date_of_registration: date
    ind_absentee: varchar
    text_registrant_id: varchar
    occupation: varchar
    text_res_address_nbr: varchar
    text_res_address_nbr_suffix: varchar
    cde_street_dir_prefix: varchar
    text_street_name: varchar
    cde_street_type: varchar
    cde_street_dir_suffix: varchar
    cde_res_unit_type: varchar
    text_res_unit_nbr: varchar
    text_res_city: varchar
    cde_res_state: varchar
    text_res_zip5: varchar
    text_res_zip4: varchar
    text_res_carrier_rte: varchar
    text_res_physical_address: varchar
    ind_res_military: varchar
    text_mail_address1: varchar
    text_mail_address2: varchar
    text_mail_address3: varchar
    text_mail_address4: varchar
    text_mail_city: varchar
    cde_mail_state: varchar
    text_mail_zip5: varchar
    text_mail_zip4: varchar
    text_mail_carrier_rte: varchar
    ind_mail_military: varchar
    ind_mail_foreign: varchar
    desc_party: varchar
    date_of_party_affiliation: varchar
    precinct_text_designation: varchar
    precinct_text_name: varchar
    precinct_part: varchar
    precinct_part_text_name: varchar
    text_phone_area_code: varchar
    text_phone_exchange: varchar
    text_phone_last_four: varchar
    voting_method_GE2016: varchar
    party_voted_GE2016: varchar
    voting_method_PE2016: varchar
    party_voted_PE2016: varchar
    voting_method_SE2016: varchar
    party_voted_SE2016: varchar
    voting_method_PP2016: varchar
    party_voted_PP2016: varchar
    voting_method_GE2014: varchar
    party_voted_GE2014: varchar
    voting_method_PE2014: varchar
    party_voted_PE2014: varchar
    voting_method_GE2012: varchar
    party_voted_GE2012: varchar
    voting_method_PE2012: varchar
    party_voted_PE2012: varchar
    voting_method_PP2012: varchar
    party_voted_PP2012: varchar
    voting_method_GE2010: varchar
    party_voted_GE2010: varchar
    voting_method_PE2010: varchar
    party_voted_PE2010: varchar
    voting_method_SE2010: varchar
    party_voted_SE2010: varchar
    voting_method_GE2008: varchar
    party_voted_GE2008: varchar
    voting_method_PE2008: varchar
    party_voted_PE2008: varchar
    voting_method_PP2008: varchar
    party_voted_PP2008: varchar
    voting_method_GE06  : varchar
    party_voted_GE06  : varchar
    voting_method_PE06  : varchar
    party_voted_PE06  : varchar
    voting_method_GE04  : varchar
    party_voted_GE04  : varchar
    voting_method_PE04  : varchar
    party_voted_PE04  : varchar
    voting_method_PP04  : varchar
    party_voted_PP04  : varchar
    perm_absentee_indicator: varchar
    desc_absentee_duration: varchar
ordered_columns:
  - county
- cde_registrant_status
- cde_registrant_reason
- cde_name_title
- text_name_first
- text_name_middle
- text_name_last
- cde_name_suffix
- year_of_birth
- date_of_registration
- ind_absentee
- text_registrant_id
- occupation
- text_res_address_nbr
- text_res_address_nbr_suffix
- cde_street_dir_prefix
- text_street_name
- cde_street_type
- cde_street_dir_suffix
- cde_res_unit_type
- text_res_unit_nbr
- text_res_city
- cde_res_state
- text_res_zip5
- text_res_zip4
- text_res_carrier_rte
- text_res_physical_address
- ind_res_military
- text_mail_address1
- text_mail_address2
- text_mail_address3
- text_mail_address4
- text_mail_city
- cde_mail_state
- text_mail_zip5
- text_mail_zip4
- text_mail_carrier_rte
- ind_mail_military
- ind_mail_foreign
- desc_party
- date_of_party_affiliation
- precinct_text_designation
- precinct_text_name
- precinct_part
- precinct_part_text_name
- text_phone_area_code
- text_phone_exchange
- text_phone_last_four
- voting_method_GE2016
- party_voted_GE2016
- voting_method_PE2016
- party_voted_PE2016
- voting_method_SE2016
- party_voted_SE2016
- voting_method_PP2016
- party_voted_PP2016
- voting_method_GE2014
- party_voted_GE2014
- voting_method_PE2014
- party_voted_PE2014
- voting_method_GE2012
- party_voted_GE2012
- voting_method_PE2012
- party_voted_PE2012
- voting_method_PP2012
- party_voted_PP2012
- voting_method_GE2010
- party_voted_GE2010
- voting_method_PE2010
- party_voted_PE2010
- voting_method_SE2010
- party_voted_SE2010
- voting_method_GE2008
- party_voted_GE2008
- voting_method_PE2008
- party_voted_PE2008
- voting_method_PP2008
- party_voted_PP2008
- voting_method_GE06
- party_voted_GE06
- voting_method_PE06
- party_voted_PE06
- voting_method_GE04
- party_voted_GE04
- voting_method_PE04
- party_voted_PE04
- voting_method_PP04
- party_voted_PP04
- perm_absentee_indicator
- desc_absentee_duration
hist_columns:
- party_voted_GE04
- party_voted_GE06
- party_voted_GE2008
- party_voted_GE2010
- party_voted_GE2012
- party_voted_GE2014
- party_voted_GE2016
- party_voted_PE04
- party_voted_PE06
- party_voted_PE2008
- party_voted_PE2010
- party_voted_PE2012
- party_voted_PE2014
- party_voted_PE2016
- party_voted_PP04
- party_voted_PP2008
- party_voted_PP2012
- party_voted_PP2016
- party_voted_SE2010
- party_voted_SE2016
#county_names:
