file_type: csv
state: ohio
source: boe
file_class: voter_file
voter_id: SOS_VOTERID
county_identifier: COUNTY_NUMBER
birthday_identifier: DATE_OF_BIRTH
voter_status: VOTER_STATUS
voter_status_active: ACTIVE
voter_status_inactive: CONFIRMATION
democratic_party: D
republican_party: R
no_party_affiliation: NPA
date_format: '%Y-%m-%d'
numeric_county: true
party_identifier: PARTY_AFFILIATION
primary_key:
  - pre_date
  - post_date
  - SOS_VOTERID
  - change_type
base_columns:
  pre_date: timestamp
  post_date: timestamp
  SOS_VOTERID: text
  change_type: text
  pre_value: text
  post_value: text
  state: text
summary_columns:
  - totals
  - date
  - state
  - ages_18_34
  - ages_35_49
  - ages_50_64
  - ages_65_130
  - r
  - npa
  - d
  - g
  - l
  - c
  - n
  - county
summary_types:
  - int
  - timestamp
  - text
  - int
  - int
  - int
  - int
  - int
  - int
  - int
  - int
  - int
  - int
  - int
  - int
additional_snapshot_columns:
  all_history: text[]
  general_history: text[]
  special_history: text[]
  primary_history: text[]
columns:
  COUNTY_NUMBER: text
  COUNTY_ID: text
  LAST_NAME: text
  FIRST_NAME: text
  MIDDLE_NAME: text
  SUFFIX: text
  DATE_OF_BIRTH: timestamp
  REGISTRATION_DATE: timestamp
  VOTER_STATUS: text
  PARTY_AFFILIATION: text
  RESIDENTIAL_ADDRESS1: text
  RESIDENTIAL_SECONDARY_ADDR: text
  RESIDENTIAL_CITY: text
  RESIDENTIAL_STATE: text
  RESIDENTIAL_ZIP: text
  RESIDENTIAL_ZIP_PLUS4: text
  RESIDENTIAL_COUNTRY: text
  RESIDENTIAL_POSTALCODE: text
  MAILING_ADDRESS1: text
  MAILING_SECONDARY_ADDRESS: text
  MAILING_CITY: text
  MAILING_STATE: text
  MAILING_ZIP: text
  MAILING_ZIP_PLUS4: text
  MAILING_COUNTRY: text
  MAILING_POSTAL_CODE: text
  CITY: text
  CITY_SCHOOL_DISTRICT: text
  COUNTY_COURT_DISTRICT: text
  PRECINCT_CODE: text
  STATE_REPRESENTATIVE_DISTRICT: text
  STATE_SENATE_DISTRICT: text
  TOWNSHIP: text
ordered_columns:
  - COUNTY_NUMBER
  - COUNTY_ID
  - LAST_NAME
  - FIRST_NAME
  - MIDDLE_NAME
  - SUFFIX
  - DATE_OF_BIRTH
  - REGISTRATION_DATE
  - VOTER_STATUS
  - PARTY_AFFILIATION
  - RESIDENTIAL_ADDRESS1
  - RESIDENTIAL_SECONDARY_ADDR
  - RESIDENTIAL_CITY
  - RESIDENTIAL_STATE
  - RESIDENTIAL_ZIP
  - RESIDENTIAL_ZIP_PLUS4
  - RESIDENTIAL_COUNTRY
  - RESIDENTIAL_POSTALCODE
  - MAILING_ADDRESS1
  - MAILING_SECONDARY_ADDRESS
  - MAILING_CITY
  - MAILING_STATE
  - MAILING_ZIP
  - MAILING_ZIP_PLUS4
  - MAILING_COUNTRY
  - MAILING_POSTAL_CODE
  - CITY
  - CITY_SCHOOL_DISTRICT
  - COUNTY_COURT_DISTRICT
  - PRECINCT_CODE
  - STATE_REPRESENTATIVE_DISTRICT
  - STATE_SENATE_DISTRICT
  - TOWNSHIP
blacklist_columns:
  - CAREER_CENTER
has_headers: YES
data_chunk_links:
  - https://www6.sos.state.oh.us/ords/f?p=VOTERFTP:DOWNLOAD::FILE:NO:2:P2_PRODUCT_NUMBER:363
  - https://www6.sos.state.oh.us/ords/f?p=VOTERFTP:DOWNLOAD::FILE:NO:2:P2_PRODUCT_NUMBER:364
  - https://www6.sos.state.oh.us/ords/f?p=VOTERFTP:DOWNLOAD::FILE:NO:2:P2_PRODUCT_NUMBER:365
  - https://www6.sos.state.oh.us/ords/f?p=VOTERFTP:DOWNLOAD::FILE:NO:2:P2_PRODUCT_NUMBER:366
county_names:
  adams: 1
  allen: 2
  ashland: 3
  ashtabula: 4
  athens: 5
  auglaize: 6
  belmont: 7,
  brown: 8
  butler: 9
  carroll: 10
  champaign: 11
  clark: 12
  clermont: 13
  clinton: 14,
  columbiana: 15
  coshocton: 16
  crawford: 17
  cuyahoga: 18
  darke: 19
  defiance: 20,
  delaware: 21
  erie: 22
  fairfield: 23
  fayette: 24
  franklin: 25
  fulton: 26
  gallia: 27,
  geauga: 28
  greene: 29
  guernsey: 30
  hamilton: 31
  hancock: 32
  hardin: 33
  harrison: 34,
  henry: 35
  highland: 36
  hocking: 37
  holmes: 38
  huron: 39
  jackson: 40
  jefferson: 41,
  knox: 42
  lake: 43
  lawrence: 44
  licking: 45
  logan: 46
  lorain: 47
  lucas: 48,
  madison: 49
  mahoning: 50
  marion: 51
  medina: 52
  meigs: 53
  mercer: 54
  miami: 55,
  monroe: 56
  montgomery: 57
  morgan: 58
  morrow: 59
  muskingum: 60
  noble: 61
  ottawa: 62,
  paulding: 63
  perry: 64
  pickaway: 65
  pike: 66
  portage: 67
  preble: 68
  putnam: 69,
  richland: 70
  ross: 71
  sandusky: 72
  scioto: 73
  seneca: 74
  shelby: 75
  stark: 76,
  summit: 77
  trumbull: 78
  tuscarawas: 79
  union: 80
  vanwert: 81
  vinton: 82
  warren: 83,
  washington: 84
